# Describes the format for available cloud services

remote_connect:
  description: Make instance UI available outside over UnioCloud cloud.

remote_disconnect:
  description: Disconnect UI from UnioCloud cloud.
